--system/userms
--123456789


/*INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'EDUARDO', 'CONTRERAS', 'LOPEZ', SYSDATE, 4, '2225863562' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'JULIAN', 'MORA', 'MARTINEZ', SYSDATE, 4, '2224783574' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'JESSICA', 'TORAL', 'COSME', SYSDATE, 4, '2334785670' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'JUAN', 'LUCAS', 'HERNANDEZ', SYSDATE, 4, '7774545752' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'ROBERTO', 'LUCAS', 'VILLA', SYSDATE, 4, '5584521247' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'ISMAEL', 'FLORES', 'LANDERO', SYSDATE, 4, '2424872120' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'JUDITH', 'ROLON', 'GARCIA', SYSDATE, 4, '2477895856' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'BRENDA', 'CONTRERAS', 'JAIMES', SYSDATE, 4, '2221784875' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'ABRIL', 'ROJAS', 'ROJAS', SYSDATE, 4, '6986354856' );
INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE_UNO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ESTATUS, NUMERO_CELULAR )
VALUES
(SEQUENCE_CLIENTES.NEXTVAL, 'ANDREA', 'MOLINA', 'HERNANDEZ', SYSDATE, 4, '9985270150' );*/

SELECT * FROM CLIENTES A;

/*UPDATE CLIENTES SET TOTAL_NOTIFICACIONES = 0, ESTATUS = 8 WHERE 
ID_CLIENTE IN (1,2,3,4,5,6,7,8,9,10);*/


SELECT * FROM NOTIFICACIONES A
ORDER BY A.ID_CLIENTE, A.TOTAL_ENVIOS ASC
;

SELECT * FROM NOTIFICACIONES A
ORDER BY A.ID_NOTIFICACION
;

--DELETE FROM NOTIFICACIONES;

SELECT * FROM SHEDLOCK A;

--DELETE FROM  shedlock;



