-------------------------------------------------------------------------
CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER(10) NOT NULL,
    NOMBRE_UNO VARCHAR2(50) NOT NULL,
    NOMBRE_DOS VARCHAR2(50),
	APELLIDO_PATERNO VARCHAR2(50),
	APELLIDO_MATERNO VARCHAR2(50),
	FECHA_REGISTRO DATE,
	TOTAL_NOTIFICACIONES NUMBER(3) DEFAULT 0,
	ESTATUS NUMBER(2) DEFAULT 0,
	NUMERO_CELULAR VARCHAR2(15),
	CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE)
);

CREATE SEQUENCE SEQUENCE_CLIENTES
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000000
    CYCLE
    CACHE 2;
-------------------------------------------------------------------------
CREATE TABLE NOTIFICACIONES(
    ID_NOTIFICACION NUMBER(10) NOT NULL,
	ID_CLIENTE NUMBER(10) NOT NULL,
    NUMERO_CELULAR VARCHAR2(15),
    ESTATUS VARCHAR2(10),
	TOTAL_ENVIOS NUMBER(2),
	FECHA_REGISTRO DATE,
    CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY(ID_NOTIFICACION),
	CONSTRAINT FK_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE SEQUENCE SEQUENCE_NOTIFICACIONES
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000000
    CYCLE
    CACHE 2;
    

-------------------------------------------------------------------------
CREATE TABLE shedlock(
  name VARCHAR(64) NOT NULL, 
  lock_until TIMESTAMP(3) NOT NULL,
  locked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), 
  locked_by VARCHAR(255) NOT NULL, 
  PRIMARY KEY (name)
);